name: supermarket_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0-91.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.13.3
  shared_preferences: ^2.2.2
  dio: ^5.3.4
  retrofit: '>=4.0.0 <5.0.0'
  logger: any
  json_annotation: ^4.8.1
  intl_utils: ^2.8.6
  flutter_localization: ^0.1.14
  freezed_annotation: ^2.4.1
  flutter_localizations:
    sdk: flutter 
  intl: any
  story_view: ^0.16.0
  qr_code_scanner: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  retrofit_generator: '>=7.0.0 <8.0.0'
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.6.2
  freezed: ^2.4.5

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/splash.png

flutter_intl:
  enabled: true
